services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/rag:/qdrant/storage
    restart: "no"

  postgres:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: diplom_db
      POSTGRES_USER: diplom_user
      POSTGRES_PASSWORD: diplom_password
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

#  ollama:
#    image: ollama/ollama:latest
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama_data:/root/.ollama
#    environment:
#      - OLLAMA_HOST=0.0.0.0:11434
#    entrypoint: ["/bin/sh", "-c"]
#    command:
#      - |
#        ollama serve &
#        sleep 5
#        ollama pull qwen3.5:4b
#        wait
#    restart: unless-stopped
#
#  ollama-embed:
#    image: ollama/ollama:latest
#    ports:
#      - "11435:11434"
#    volumes:
#      - ollama_embed_data:/root/.ollama
#    environment:
#      - OLLAMA_HOST=0.0.0.0:11434
#    entrypoint: ["/bin/sh", "-c"]
#    command:
#      - |
#        ollama serve &
#        sleep 5
#        ollama pull qwen3-embedding:0.6b
#        wait
#    restart: unless-stopped

volumes:
  postgres_data:
#  ollama_data:
#  ollama_embed_data:
