services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/rag:/qdrant/storage
    restart: "no"

  postgres:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: diplom_db
      POSTGRES_USER: diplom_user
      POSTGRES_PASSWORD: diplom_password
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data:
